export const elements = {
    habitNaam: document.getElementById("habit-name"),
    habitdesc: document.getElementById("habit-desc"),
    habitCreatebtn: document.getElementById("add-habit"),
    habitList: document.getElementById("habits-list"),
    plusBtn: document.getElementById("add-habit-btn"),
    habitModal: document.getElementById("habit-modal"),
    modalCancelBtn: document.getElementById("close-modal-btn"),
    createBtn: document.getElementById("confirm-btn"),
    modalTitle: document.getElementById("modal-title"),
    deleteBtn: document.getElementById("delete-btn"),
    modal: document.getElementsByClassName("modal"),
    habitModal1: document.getElementById("habit-detail-modal"),
    modalTitle1: document.getElementById("detail-title"),
    habitDescInput: document.getElementById("habit-desc"),
    deleteBtn1: document.getElementById("delete-btn1"),
    closeBtn: document.getElementById("close-modal-btn1"),
    habitDetailModal: document.getElementById("habit-detail-modal"),
    detailTitle: document.getElementById("detail-title"),
    detailDesc: document.getElementById("detail-desc"),
    deleteHabitBtn: document.getElementById("delete-habit-btn"),
    completHabit: document.getElementById("completed-today"),
    habitconfirmBtn: document.getElementById("delete-habit-btn1"),
    delhabitmenu: document.getElementById("delhabit"),
    detailNoteTextarea: document.getElementById("daily-note"),
    detailCheckbox: document.getElementById("completed-today"),
    completeTodayBtn: document.getElementById("complete-today-btn"),
    detailStreak: document.getElementById("detailStreak")
}

